Add version increment v11

diff --git a/.github/workflows/tag-and-version.yml b/.github/workflows/tag-and-version.yml
--- a/.github/workflows/tag-and-version.yml
+++ b/.github/workflows/tag-and-version.yml
@@ -1,14 +1,16 @@
-name: Build and tag Rust project
+name: tag-and-version
 
 on:
   push:
     branches:
       - master
-      - "!github-actions[bot]"
+    paths:
+      - "**.rs"
   workflow_dispatch:
 
 jobs:
   tag:
+    if: github.actor != 'github-actions[bot]'
     name: ${{ github.actor }} authorized build and tag
     runs-on: ubuntu-latest
     steps:
@@ -17,25 +19,30 @@ jobs:
         with:
           persist-credentials: false
 
+      - name: Get package version
+        run: |
+          PACKAGE_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
+
       - name: Generate new version
         uses: anothrNick/github-tag-action@1.64.0
         env:
           GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
           DEFAULT_BUMP: patch
+          INITIAL_VERSION: ${{ env.PACKAGE_VERSION }}
           DRY_RUN: true
         id: bump_version
 
       - name: Set package version
         run: |
-          cargo install cargo-edit
-          cargo set-version ${{ steps.bump_version.outputs.new_tag }}
+          sed -i".bak" '/^version =/ s/="[^"]*"$/="'"${{ steps.bump_version.outputs.new_tag }}"'"/' Cargo.toml
 
-      - name: Tag
-        uses: anothrNick/github-tag-action@1.64.0
-        env:
-          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
-          WITH_V: true
-          DEFAULT_BUMP: patch
+          if [[ $? != 0 ]]; then
+              echo "ERROR: Failed to update the version number in Cargo.toml" >&2
+              exit 1
+          else
+              echo "Successfully updated the version number in Cargo.toml to ${{ steps.bump_version.outputs.new_tag }}"
+          fi
 
       - name: Commit
         env:
@@ -44,11 +51,5 @@ jobs:
           git config --global user.email "github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
           git commit -am "chore: bump version to ${{ steps.bump_version.outputs.new_tag }}"
-
-      - name: Push
-        uses: ad-m/git-push-action@master
-        with:
-          github_token: ${{ secrets.MY_TOKEN }}
-          branch: ${{ github.ref }}
-
-
+          git tag v"${{ steps.bump_version.outputs.new_tag }}"
+          git push origin ${{ github.ref }} --follow-tags
